### ISSUE TITLE
Error in loading the API key from config file

### ISSUE THREAD

**Issue by tytung2020** [lamini-ai/lamini#15]
Traceback (most recent call last):
  File "C:\Users\tytun\desktop\Lamini_test.py", line 9, in <module>
    llm(test, output_type=Test)
  File "C:\Users\tytun\AppData\Local\Programs\Python\Python310\lib\site-packages\llama\program\builder.py", line 48, in __call__
    return run(value)
  File "C:\Users\tytun\AppData\Local\Programs\Python\Python310\lib\site-packages\llama\program\value.py", line 185, in gen_value
    value._compute_value()
  File "C:\Users\tytun\AppData\Local\Programs\Python\Python310\lib\site-packages\llama\program\value.py", line 72, in _compute_value
    response = query_run_program(params)
  File "C:\Users\tytun\AppData\Local\Programs\Python\Python310\lib\site-packages\llama\program\util\run_ai.py", line 10, in query_run_program
    key, url = get_url_and_key()
  File "C:\Users\tytun\AppData\Local\Programs\Python\Python310\lib\site-packages\llama\program\util\run_ai.py", line 111, in get_url_and_key
    key = cfg["production.key"]
  File "C:\Users\tytun\AppData\Local\Programs\Python\Python310\lib\site-packages\config\configuration_set.py", line 110, in __getitem__
    return self._from_configs("__getitem__", item)
  File "C:\Users\tytun\AppData\Local\Programs\Python\Python310\lib\site-packages\config\configuration_set.py", line 67, in _from_configs
    raise last_err
  File "C:\Users\tytun\AppData\Local\Programs\Python\Python310\lib\site-packages\config\configuration_set.py", line 61, in _from_configs
    values.append(getattr(config_, attr)(*args, **kwargs))
  File "C:\Users\tytun\AppData\Local\Programs\Python\Python310\lib\site-packages\config\configuration.py", line 155, in __getitem__
    raise KeyError(item)
KeyError: 'production.key'

Lamini_test.py contain only the code in Basic test section of https://lamini-ai.github.io/#setup-your-keys.
The config file is in desktop/.powerml/

**Comment by ninazwei90** [comment]
hey! @tytung2020 thanks for your understanding of our delayed response. Have you resolved this issue yet? If not, can you try again and share the code too? So we can help you investigate.

Also, thanks so much for using Lamini and reporting issues! We'd love to learn from you and see how we can improve Lamini for you! If you're open to a 20-30 min chat (in exchange for Lamini free credits), please email me at nina@lamini.ai. Looking forward!!
